### ISSUE TITLE
Page Header Text Getting Cut Off

### ISSUE THREAD

**Issue by AbdullahMunawar** [AppSecUSA2016/Website-Stuff#6]
Look at Register page. The 'i' is cutting cut off at the top from the Venue page.

**Comment by pjcoole** [comment]
Need to find way to remove default Page Title.

**Comment by pjcoole** [comment]
Updated style.css to add necessary padding for h1 and h3.  Also updated some top padding on divs to correct same issue for mobile and tablet views.
